# Generated by Django 6.0.6 on 2026-06-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accaunt',
            new_name='Account',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='accaunt',
            new_name='account',
        ),
    ]
