# Generated by Django 6.0.6 on 2026-06-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_note_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('PENDING', 'На проверке'), ('PUBLISHED', 'Опубликовано'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=20),
        ),
    ]
